<?php

namespace AnswersBundle\Entity;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedById() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AnswersBundle:Answer a ORDER BY a.id ASC'
            )
            ->getResult();
    }
}
