<?php

namespace AnswersBundle\Entity;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Show Comment Attachments
     * @param $id
     * @return mixed
     */
    public function showCommentAttachments($id) {
        $comment = $this->getDoctrine()
            ->getRepository("AnswersBundle:Comment")
            ->find($id);

        $attachments = $comment->getAttachments();

        return $attachments;
    }
}
